export const ART_TYPES = {
    PAINTING: 'PAINTING',
    PHOTO: 'PHOTO',
    SCULPTURE: 'SCULPTURE'
}

export const ART_STATUS = {
    AVAILABLE: 'AVAILABLE',
    SOLD: 'SOLD',
    CART: 'CART'
}

export const ORDER_STATUS = {
    CREATED: 'CREATED',
    PROGRESS: 'PROGRESS',
    FINISHED: 'FINISHED'
}

export const NULL = 'null'

export const CHARACTER_RESTRICTION = {
    ARTIST_NAME: 100,
    ARTIST_DESCRIPTIONS: 500,
    NAME: 100,
    CUSTOMER_DESCRIPTION: 200,
    ART_NAME: 200,
    ART_DESCRIPTION: 500,
    TAG_LENGTH: 30,
    TAG_COUNT: 22,
    MATERIAL_LENGTH: 20,
    MATERIAL_COUNT: 30,
    POST_TITLE: 200,
    POST_TEXT: 500,
    ART_PHOTO_COUNT: 5,
    CARD: 20,
    ADDRESS_NAME: 200,
    ADDRESS_COUNTRY: 200,
    ADDRESS_REGION: 200,
    ADDRESS_CITY: 200,
    ADDRESS_LOCATION: 200
}