export const ROLES = {
    ARTIST: 'artist',
    CUSTOMER: 'customer'
}

export const PATHS_CATEGORY = {
    ARTIST: '/artist',
    CUSTOMER: '/customer',

    CREATE: '/create',

    MAIN: '/main',
    AUTH: '/auth',
    PROFILE: '/profile',
    SETTINGS: '/settings',
    ART: '/art',
    ARTISTS: '/artists',
    PAINTINGS: '/paintings',
    PHOTO: '/photo',
    SCULPTURES: '/sculptures',
    SEARCH: '/search',
    CART: '/cart',
    SUBSCRIPTIONS: '/subscriptions',

    ERROR_404: '/404'
}

export const MAIN_PATHS = {
    MAIN: PATHS_CATEGORY.MAIN,
    AUTH: PATHS_CATEGORY.AUTH,

    PROFILE_CUSTOMER: PATHS_CATEGORY.PROFILE + PATHS_CATEGORY.CUSTOMER,
    PROFILE_ARTIST: PATHS_CATEGORY.PROFILE + PATHS_CATEGORY.ARTIST,
    CREATE_CUSTOMER: PATHS_CATEGORY.CREATE + PATHS_CATEGORY.CUSTOMER,
    CREATE_ARTIST: PATHS_CATEGORY.CREATE + PATHS_CATEGORY.ARTIST,
    PROFILE: PATHS_CATEGORY.PROFILE,

    SETTINGS: PATHS_CATEGORY.SETTINGS,

    ARTISTS: PATHS_CATEGORY.ARTISTS,

    PAINTINGS: PATHS_CATEGORY.PAINTINGS,
    PHOTO: PATHS_CATEGORY.PHOTO,
    SCULPTURES: PATHS_CATEGORY.SCULPTURES,
    CREATE_ART: PATHS_CATEGORY.CREATE + PATHS_CATEGORY.ART,
    
    SEARCH: PATHS_CATEGORY.SEARCH,

    CART: PATHS_CATEGORY.CART,
    SUBSCRIPTIONS: PATHS_CATEGORY.SUBSCRIPTIONS,

    ONE_PAINTING: PATHS_CATEGORY.PAINTINGS + '/[id]',
    ONE_PHOTO: PATHS_CATEGORY.PHOTO + '/[id]',
    ONE_SCULPTURE: PATHS_CATEGORY.SCULPTURES + '/[id]',
}